language: android
env:
  matrix:

    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a


android:
  components:
    - build-tools-21.1.1
    - extra-google-google_play_services

script: "./gradlew build"

